name: Tests
on:
  push:
    branches:
      - master
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4.10
          - 2.5.9
          - 2.6.10
          - 2.7.8
          - 3.0.6
          - 3.1.4
          - 3.2.2
        rails:
          - 4.2.0
          - 5.0.0
          - 5.1.0
          - 5.2.0
          - 6.0.0
          - 6.1.0
          - 7.0.0
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up database schema
        run: bundle exec rake db:migrate --trace
      - name: Run tests
        run: bundle exec rspec spec
